### ISSUE TITLE
How to generate our own datasets for training and inference stage?

### ISSUE THREAD

**Issue by zhihaoyi** [lhaippp/RecDiffusion#11]
Hi! That was a great work proposed by your team!

I am wondering how I am supposed to generate our own dataset from two individual images to a rectangle stitched image with M_s?

**Comment by lhaippp** [comment]
Hi,

for the image stiching step, you could try [UDIS2](https://github.com/nie-lang/UDIS2), I think you could as well obtain a corresponding M_s. BTW, if you have an already stiching image without M_s, you could consider using this function  [define_mask_zero_borders](https://github.com/PruneTruong/DenseMatching/blob/b054fe9f7988c70db1e0e7347d0b1bafe135cc27/utils_flow/img_processing_utils.py#L7) to generate one

**Comment by zhihaoyi** [comment]
Thank you for your information! I will definitely try it out! 

Besides that, I am also wondering how to collect the training dataset. In the training dataset, we have rectangular images as GT and non-rectangular stitched images as inputs, but I am confused how we can obtain those pairs. Do we generate non-rectangular stitched images from GT using manually crafted motion fields?

**Comment by lhaippp** [comment]
hi,
you could refer to [Deep Rectangling for Image Stitching: A Learning Baseline](https://arxiv.org/abs/2203.03831) for more detail about creating dataset.
