### ISSUE TITLE
您好，这个代码复现训练必须在跟您的配置一样的情况下才可以吗？

### ISSUE THREAD

**Issue by luhan225** [lhaippp/RecDiffusion#9]

**Comment by lhaippp** [comment]
It shoud be the same, did you meet some problem?

**Comment by luhan225** [comment]
> It shoud be the same, did you meet some problem?

Because your paper mentioned that 8 A100 configurations are required to run, but I am currently unable to provide this configuration, I would like to know if it can run with a low configuration。

**Comment by lhaippp** [comment]
For inference, one single 3090 is enough. And for training, you can try to reduce the batch size related to your GPU memory, it takes longer training time but I think the performance could be comparable
